deployment:
  tasks:
    # 1. Definir la ruta de despliegue
    - export DEPLOYPATH=/home3/peguero/public_html/repser.mx/app

    # 2. Copiar los archivos del repo al directorio público
    - /bin/cp -R * $DEPLOYPATH

    # 3. Entrar al directorio de despliegue
    - cd $DEPLOYPATH

    # 4. Instalar dependencias de Composer
    - /usr/local/bin/composer install --no-dev --optimize-autoloader

    # 5. Limpiar y cachear configuración
    - php artisan config:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

    # 6. Ejecutar migraciones en producción
    - php artisan migrate --force